<net.sf.textbeans.parser.testobj.TMultipleSimpleOrder__Batch>
  <orders class="tree-set">
    <no-comparator/>
    <net.sf.textbeans.parser.testobj.TMultipleSimpleOrder__Order>
      <id>US00000001</id>
      <feeBd>1</feeBd>
      <feeLong>1</feeLong>
      <feeIntPrimitive>1</feeIntPrimitive>
      <feeStr>1</feeStr>
    </net.sf.textbeans.parser.testobj.TMultipleSimpleOrder__Order>
    <net.sf.textbeans.parser.testobj.TMultipleSimpleOrder__Order>
      <id>US00000002</id>
      <feeBd>2</feeBd>
      <feeLong>2</feeLong>
      <feeIntPrimitive>2</feeIntPrimitive>
      <feeStr>2</feeStr>
    </net.sf.textbeans.parser.testobj.TMultipleSimpleOrder__Order>
    <net.sf.textbeans.parser.testobj.TMultipleSimpleOrder__Order>
      <id>XX00000003</id>
      <feeBd>3</feeBd>
      <feeLong>3</feeLong>
      <feeIntPrimitive>3</feeIntPrimitive>
      <feeStr>3</feeStr>
    </net.sf.textbeans.parser.testobj.TMultipleSimpleOrder__Order>
  </orders>
</net.sf.textbeans.parser.testobj.TMultipleSimpleOrder__Batch>