<linked-list>
  <net.sf.textbeans.parser.testobj.TSingleTokenToMultiFields__Order>
    <id>US11261048</id>
    <feeBd>3</feeBd>
    <feeLong>3</feeLong>
    <feeIntPrimitive>3</feeIntPrimitive>
    <feeStr>3</feeStr>
  </net.sf.textbeans.parser.testobj.TSingleTokenToMultiFields__Order>
</linked-list>