package net.sf.textbeans.beaver;

import java.util.ArrayList;
import beaver.*;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "OneLineExample.beaver".
 */
public class TextbeansParser extends Parser {
	static public class Terminals {
		static public final short EOF = 0;
		static public final short fee = 1;
		static public final short id = 2;
		static public final short at = 3;
	}

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9nrZKaEW30C0uUqfMpYpRoRBRXHhrYQM8wi1DZzONGdKqcOdnH$$GQ$c81194rJeqH2RPH" +
		"XFWYbdfjgsuj5h6Bh7Ml#HrU93rdtShW5umVp1XCI");

	static final Action RETURN3 = new Action() {
		public Symbol reduce(Symbol[] _symbols, int offset) {
			return _symbols[offset + 3];
		}
	};

	static final Action RETURN2 = new Action() {
		public Symbol reduce(Symbol[] _symbols, int offset) {
			return _symbols[offset + 2];
		}
	};

	private final Action[] actions;

	public TextbeansParser() {
		super(PARSING_TABLES);
		actions = new Action[] {
			Action.RETURN,	// [0] batch = order
			RETURN3,	// [1] order = id at fee; returns 'fee' although none is marked
			Action.RETURN,	// [2] order = id
			RETURN2,	// [3] order = id fee; returns 'fee' although none is marked
			RETURN2	// [4] order = fee id; returns 'id' although none is marked
		};
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
